name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Translate secrets of base64 into json
        env:
          ADMIN_SDK_TOKEN: ${{ secrets.ADMIN_SDK_TOKEN }}

        run: |
          echo-n $ADMIN_SDK_TOKEN | base64 --decode > ./src/admin-sdk-token.key.json
      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Build
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: lib
          path: lib
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Translate secrets of base64 into json
        env:
          ADMIN_SDK_TOKEN: ${{ secrets.ADMIN_SDK_TOKEN }}

        run: |
          echo-n $ADMIN_SDK_TOKEN | base64 --decode > ./src/admin-sdk-token.key.json
      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: lib
          path: lib
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}